### This workflow will build documentation (but not publish it) to ensure that documentation can
### still be built without issue.

name: build-docs

on:
  repository_dispatch:
    types: build-docs
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

# TODO: Avoid manually copying publish-docs' steps as done below - at the time of writing,
#       there's supposedly no clean way to do this in GitHub Actions. Ideally there should
#       be a single helper action that builds documentation - that would be called by both
#       this action as well as publish-docs.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-markdown-builder

      - name: Generate documentation
        run: |
          python -m sphinx.cmd.build -b markdown docs docs/_build
          mv docs/_build/_api/* docs/_build/
          mv docs/images/* docs/_build/
