### This workflow will generate documentation to update the GitHub Wiki accordingly.

name: publish-docs

on: # TODO: Have this run on new releases.
  repository_dispatch:
    types: publish-docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-markdown-builder

      - name: Generate documentation
        run: |
          python -m sphinx.cmd.build -b markdown docs docs/_build -W
          python -c "import gmplot.utility; gmplot.utility._pretty_format_markdown('docs/_build/_api/')"
          mv docs/_build/_api/* docs/_build/
          mv docs/images/* docs/_build/

      - name: Publish to GitHub Wiki
        uses: gmplot/github-wiki-publish-action@rsync
        with:
          path: docs/_build
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        # TODO: This uses an unreleased version of the publish action - once that action's
        #       functionality is merged and released, the version used here should be updated
        #       with SwiftDocOrg's.
